version: "3.7"

services:
  db:
    image: citusdata/citus:11.0
    command: -c 'log_min_messages=notice'
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      PGPORT: ${POSTGRES_DB_PORT:-5432}
    ports:
      - 5432:5432

#  migration:
#    image: postgres
#    restart: "no"
#    env_file: .env
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB_NAME}
#      POSTGRES_USER: ${POSTGRES_DB_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
#      PGPORT: ${POSTGRES_DB_PORT:-5432}
#    volumes:
#      - ./migrate-db.sh:/opt/src/migrate-db.sh:ro
#      - ./migrations:/opt/src/migrations:ro
#    working_dir: /opt/src
#    command: sh -c "sh migrate-db.sh"
#    depends_on:
#      - db
